In [2]:
from sklearn.datasets import load_iris
import pandas as pd
import random
import numpy as np
import matplotlib.pyplot as plt

from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.model_selection import train_test_split

In [4]:
data = load_iris()
columns = data.feature_names

data2=pd.DataFrame(data.data)
data2.columns = columns
data2['target'] = data.target
data2.shape

(150, 5)

# Spliting data based on target variable greter than 0 for two cases virginica and versicolor

In [5]:
data3 = data2[data2.target > 0]
data3.shape

(100, 5)

In [6]:
data3

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
50        1  
51        1  
52        1  
53        1  
54        1  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[100 rows x 5 columns]

In [7]:
versicolor = data3[data3.target == 1]
verginica =  data3[data3.target == 2]

versicolor_train, versicolor_test, versicolor_target_train, versicolor_target_test = train_test_split(
    versicolor[versicolor.columns[:-1]], versicolor[versicolor.columns[-1]], test_size=0.2, random_state=42)

verginica_train, verginica_test, verginica_target_train, verginica_target_test = train_test_split(
    verginica[verginica.columns[:-1]], verginica[versicolor.columns[-1]], test_size=0.2, random_state=42)

# Answer 3a 

In [8]:
training_data_X = pd.concat([versicolor_train,verginica_train],ignore_index=True)
testing_data_X = pd.concat([versicolor_test,verginica_test],ignore_index=True)

training_data_y = pd.concat([versicolor_target_train,verginica_target_train],ignore_index=True)
testing_data_y = pd.concat([versicolor_target_test,verginica_target_test],ignore_index=True)

# Feature Scaling

In [9]:

sc = StandardScaler()
X_train = sc.fit_transform(training_data_X)
X_test = sc.transform(testing_data_X)

# Ans 3 b: different classification model

In [10]:
logistic_regression_classifier = LogisticRegression(random_state = 42)

svm_linear_classifier = SVC(kernel = 'linear', random_state = 42)

svm_poly_classifier = SVC(kernel = 'poly', random_state = 42)

svm_rbf_classifier = SVC(kernel = 'rbf', random_state = 42)

# Ans 3c: Confusion matrix and Accuracy for different models

In [ ]:
# Logistic Regression

In [19]:
logistic_regression_classifier.fit(X_train, training_data_y)
y_pred_LR = logistic_regression_classifier.predict(X_test)
print("confusion Matrix")
print(confusion_matrix(testing_data_y,y_pred_LR))
print("Accuracy")
print(accuracy_score(testing_data_y, y_pred_LR))

confusion Matrix
[[10  0]
 [ 0 10]]
Accuracy
1.0


# Linear SVM

In [20]:
svm_linear_classifier.fit(X_train, training_data_y)
y_pred_linear_SVM = svm_linear_classifier.predict(X_test)
print("confusion Matrix")
print(confusion_matrix(testing_data_y,y_pred_linear_SVM))
print("Accuracy")
print(accuracy_score(testing_data_y, y_pred_linear_SVM))

confusion Matrix
[[10  0]
 [ 0 10]]
Accuracy
1.0


# poly SVM

In [21]:
svm_poly_classifier.fit(X_train, training_data_y)
y_pred_poly_SVM = svm_poly_classifier.predict(X_test)
print("confusion Matrix")
print(confusion_matrix(testing_data_y,y_pred_poly_SVM))
print("Accuracy")
print(accuracy_score(testing_data_y, y_pred_poly_SVM))

confusion Matrix
[[10  0]
 [ 2  8]]
Accuracy
0.9


# RBF SVM

In [22]:
svm_rbf_classifier.fit(X_train, training_data_y)
y_pred_rbf_SVM = svm_rbf_classifier.predict(X_test)
print("confusion Matrix")
print(confusion_matrix(testing_data_y,y_pred_rbf_SVM))
print("Accuracy")
print(accuracy_score(testing_data_y, y_pred_rbf_SVM))

confusion Matrix
[[10  0]
 [ 1  9]]
Accuracy
0.95
